services:

  aaugrader:
    build: 
      context: ./src/binary/
      args:
        - BINARY_NAME=aaugrader
    ports:
      - "8000:8000"
    expose:
      - "8000"
      
  aaugrader_rop:
    build: 
      context: ./src/binary/
      args:
        - BINARY_NAME=aaugrader_rop
    ports:
      - "8001:8000"
    expose:
      - "8001"
        
  ids:
    build: ./src/detection/
    ports:
      - "8080:8080"
    expose:
      - "8080"
