services:
  aaugrader:
    build: 
      context: ./src/binary/
      network: host
      args:
        - BINARY_NAME=aaugrader
        - RUN_SCRIPT=aaugrader.sh
    ports:
      - "8000:8000"
    expose:
      - "8000"
      
  aaugrader_rop:
    build: 
      context: ./src/binary/
      network: host
      args:
        - BINARY_NAME=aaugrader_rop
        - RUN_SCRIPT=aaugrader.sh
    ports:
      - "8001:8000"
    expose:
      - "8001"
       
  ids:
    build: ./src/detection/
    ports:
      - "8080:8080"
    expose:
      - "8080"
